Modifications to WW3 for drag coefficient in the Med Sea
CMCC-Foundation/WW3 pull request #1
Opened 2023-02-09 10:10 UTC by francescococetta

# Pull Request Summary
 

## Description

### Issue(s) addressed

### Commit Message

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

2023-02-09 10:43 UTC, daniele-peano requested changes
I put some comments for cleaning the code

2023-02-09 10:43 UTC, daniele-peano commented on README.md
> +###### FC
you can remove this now

2023-02-09 10:43 UTC, daniele-peano commented on model/src/constants.F90
> +!      REAL, PARAMETER         :: KAPPA = 0.40       !Von Karman's constant
you can remove these two commented lines

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3iogomd.F90
> +        J = 2
do you want to change this value?

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3ounfmetamd.F90
>        META => GROUP(10)%FIELD(1)%META
You could keep a group 11 for the user_defined case.

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +!      INTEGER, PARAMETER      :: IUSTAR=100,IALPHA=200, ILEVTAIL=50
Remove these commented lines

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +!      REAL,    PARAMETER      :: TAUWMAX = 2.2361 !SQRT(5.)
remove this commented line

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      !Usigma=MAX(0.,-0.025*AS)
you can delete these lines if you don't need them.

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      !IF (ISTAB.EQ.1) UST=USTAR*(1.-USTARsigma)
you can delete these lines if you don't need them

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      !YSTRESS=0.5*(STRESSSTAB(1,2)+STRESSSTAB(2,2))
you can delete these lines if you don't need them

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      XJ=MAX(0.,(GRAV*Z0/MAX(UST,0.00001)**2-AALPHA) / DELALP) ! AIMIE already MAX(UST,0.00001)
you can remove the comment

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      !INTEGER, PARAMETER      :: JTOT=250
you can remove this commented line

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      !ALPHAM = 20.*AALPHA
you can remove this commented line

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +            !IF (ZZ0MAX.NE.0) ZZ00=MIN(ZZ00,ZZ0MAX)
you can remove this line

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +               !TAUHFT(K,L)  = TAUHFT(K,L)+W(J)*ZBETA/Y*DELY
you can remove this commented line

2023-02-09 10:43 UTC, daniele-peano commented on model/src/w3src3md.F90
> +      DELJ1   = MIN(1.,XJ - REAL(J))    !AIMIE alreydy corrected
you can remove the comment

2023-02-09 11:10 UTC, francescococetta commented on model/src/w3iogomd.F90
> +        J = 2
yes, when 'U2' J=2

2023-02-09 11:14 UTC, francescococetta commented on model/src/w3ounfmetamd.F90
>        META => GROUP(10)%FIELD(1)%META
done!

2023-02-10 08:44 UTC, daniele-peano requested changes

2023-02-10 08:44 UTC, daniele-peano commented on model/src/w3src3md.F90
>  #ifdef W3_STAB3
Remove also these #ifdef -> #endif lines

2023-02-10 08:57 UTC, daniele-peano approved these changes

2023-02-10 08:57 UTC, merged